"""Add role column to Admin and Employee tables

Revision ID: 6e64d635fabf
Revises: 8fbf2849764e
Create Date: 2025-08-16 20:00:45.605429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e64d635fabf'
down_revision: Union[str, Sequence[str], None] = '8fbf2849764e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
