"""Set server default for role on employee and admin tables

Revision ID: 76b049b9b7e6
Revises: c746a9849cb9
Create Date: 2025-08-16 20:36:37.177413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76b049b9b7e6'
down_revision: Union[str, Sequence[str], None] = 'c746a9849cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
