"""add status column to subtask

Revision ID: c28159fdfb37
Revises: 8e1ba32182b4
Create Date: 2025-08-19 14:25:25.337565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c28159fdfb37'
down_revision: Union[str, Sequence[str], None] = '8e1ba32182b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtask', sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='subtaskstatus'), nullable=False))
    op.drop_column('subtask', 'is_assigned')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtask', sa.Column('is_assigned', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('subtask', 'status')
    # ### end Alembic commands ###
