"""Set server default for role on employee and admin tables

Revision ID: c746a9849cb9
Revises: 0b1749d81974
Create Date: 2025-08-16 20:27:51.954311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c746a9849cb9'
down_revision: Union[str, Sequence[str], None] = '0b1749d81974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
