"""update employee status default

Revision ID: ee40efc4f668
Revises: 
Create Date: 2025-08-16 19:12:26.543328

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ee40efc4f668'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'status',
               existing_type=mysql.ENUM('active', 'inactive'),
               type_=sa.Enum('available', 'unavailable', name='employeestatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'status',
               existing_type=sa.Enum('available', 'unavailable', name='employeestatus'),
               type_=mysql.ENUM('active', 'inactive'),
               existing_nullable=False)
    # ### end Alembic commands ###
